### ISSUE TITLE
Fix mvn install.

### ISSUE THREAD

**Issue by zhengrenjie** [zhengrenjie/catty#22]
'mvn install' will not pass. Might be caused by improper unit-tests.

It is so weird that if run 'mvn test' everything is ok when 'mvn install' not. Running 'mvn install' the test will not pass.

```
io.catty.core.extension.ExtensionNotFoundException: Extension type: io.catty.core.extension.spi.InvokerChainBuilder name: DIRECT
        at io.catty.core.extension.ExtensionFactory.getExtensionSingleton(ExtensionFactory.java:202)
        at io.catty.core.extension.ExtensionFactory.getExtensionSingleton(ExtensionFactory.java:212)
        at io.catty.config.Exporter.registerService(Exporter.java:89)
        at io.catty.test.BasicTest.init(BasicTest.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
        ......
```

**Comment by zhengrenjie** [comment]
Done.
This is a bug, because ExtensionFactory would not scan jar, so some extension can't be found.
It has been fixed.
